services:
    backend:
        build: "backend-api/simple-api-student-main"
        networks:
            - my-network
        depends_on:
            - database
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        ports:
            - "8080:8080"

    database:
        build: "database"
        networks:
            - my-network
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    httpd:
        build: "http-server"
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - backend

networks:
    my-network:
    
